---
- name: Notify administrators
  ansible.builtin.debug:
    msg:
      - "TO: {{ admin }}"
      - "Subject: Host {{ inventory_hostname }} provisioned."
  loop: "{{ srp_notify_host_admins }}"
  loop_control:
    loop_var: admin
