---
- name: Make sure packages are present
  ansible.builtin.include_role:
    name: solid.example.srp_packages

- name: Notify administrators
  ansible.builtin.include_role:
    name: solid.example.srp_notify

- name: Add host to change management database
  ansible.builtin.include_role:
    name: solid.example.srp_cmdb
