---
- name: Add host to change management database
  ansible.builtin.lineinfile:
    name: CMDB.txt
    line: "{{ inventory_hostname }}"
    create: true
    owner: "{{ omit }}"
    mode: "{{ omit }}"
