---
galaxy_info:
  author: Kirill Satarin (@kksat)
  description: Ansible role to demonstrate open close SOLID principle
  license: GPL-3.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: Void Linux
      versions:
        - all
  galaxy_tags: []
dependencies: []
