---
- name: Make sure packages are present
  ansible.builtin.lineinfile:
    name: "{{ inventory_hostname }} - packages.txt"
    create: true
    line: "{{ package.name }}=={{ package.version }}"
    owner: "{{ omit }}"
    mode: "{{ omit }}"
  loop: "{{ srp_packages_list }}"
  loop_control:
    loop_var: package
