---
- name: Make sure packages are present
  ansible.builtin.lineinfile:
    name: "{{ inventory_hostname }} - packages.txt"
    create: true
    line: "{{ package.name }}=={{ package.version }}"
  loop: "{{ srp_packages }}"
  loop_control:
    loop_var: package
