---
- name: This is the main entry point
  ansible.builtin.debug:
    var: liskov_substitution_param

- name: Include tasks from the task file
  ansible.builtin.include_role:
    name: solid.example.liskov_substitution
    tasks_from: left
  vars:
    liskov_substitution_left: "{{ liskov_substitution_param }}"
