---
- name: Run examples to illustrate dependency inversion principle in ansible
  hosts: localhost
  gather_facts: false
  vars: {}
  tasks:
    - name: Show copyright # noqa: run-once[task]
      solid.example.show_c:
      run_once: true

    - name: Show warranty # noqa: run-once[task]
      solid.example.show_w:
      run_once: true

    - name: Run dependency_inversion role
      ansible.builtin.include_role:
        name: solid.example.dependency_inversion
        tasks_from: left
