---
- name: Run left examples to illustrate 'Liskov substitution' principle in ansible
  hosts: all
  gather_facts: false
  vars: {}
  tasks:
    - name: Show copyright # noqa: run-once[task]
      solid.example.show_c:
      run_once: true

    - name: Show warranty # noqa: run-once[task]
      solid.example.show_w:
      run_once: true

    - name: Run liskov_substitution role
      ansible.builtin.include_role:
        name: solid.example.liskov_substitution
        tasks_from: left
      vars:
        liskov_substitution_left: Hello DevConf 2024!
